---

plugins:
  - eslint-plugin-import

env:
  node: true

extends:
  - 'airbnb-base'

rules:
  no-console: 0
  no-unused-vars: 0
  import/no-extraneous-dependencies: [error, { devDependencies: true }]
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
